import { Platform, StatusBar, StyleSheet } from "react-native";

export const palette = {
  background: "#000000",
  card: "#000000",
  surface: "#000000",
  surfaceAlt: "#050505",
  border: "#141414",
  borderSoft: "#262626",
  accent: "#A8FF60",
  accentSoft: "#182308",
  accentText: "#F7FFE8",
  text: "#FFFFFF",
  textMuted: "#B8B8B8",
  textSubtle: "#6E6E6E",
  secondaryButton: "#050505",
  positive: "#A8FF60",
  warning: "#FFD76A",
  danger: "#FF7A7A",
};

const topInset = Platform.OS === "android" ? (StatusBar.currentHeight ?? 0) + 8 : 8;

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: palette.background,
  },
  container: {
    flex: 1,
    backgroundColor: palette.background,
  },
  content: {
    alignItems: "center",
    paddingHorizontal: 20,
    paddingBottom: 28,
    paddingTop: topInset + 14,
    gap: 18,
  },
  hero: {
    width: "100%",
    maxWidth: 640,
    gap: 14,
  },
  heroCard: {
    width: "100%",
    borderRadius: 30,
    padding: 22,
    gap: 18,
    backgroundColor: palette.card,
    borderWidth: 1,
    borderColor: palette.border,
  },
  headerRow: {
    gap: 12,
  },
  headerActions: {
    alignItems: "flex-start",
  },
  titleBlock: {
    flex: 1,
    gap: 8,
  },
  eyebrow: {
    color: palette.textSubtle,
    fontSize: 11,
    textTransform: "uppercase",
    letterSpacing: 2.2,
  },
  title: {
    color: palette.text,
    fontSize: 36,
    fontWeight: "800",
  },
  subtitle: {
    color: palette.textMuted,
    fontSize: 15,
    lineHeight: 24,
  },
  heroBadgeRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  statusBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    borderRadius: 999,
    paddingVertical: 9,
    paddingHorizontal: 12,
    borderWidth: 1,
  },
  statusBadgePositive: {
    backgroundColor: "#0A1204",
    borderColor: "#22320E",
  },
  statusBadgeNeutral: {
    backgroundColor: palette.surfaceAlt,
    borderColor: palette.border,
  },
  statusBadgeWarning: {
    backgroundColor: "#181206",
    borderColor: "#3A2F13",
  },
  statusBadgeDanger: {
    backgroundColor: "#231313",
    borderColor: "#422424",
  },
  statusBadgeText: {
    color: palette.text,
    fontSize: 12,
    fontWeight: "700",
  },
  statusDot: {
    width: 8,
    height: 8,
    borderRadius: 999,
  },
  statusDotPositive: {
    backgroundColor: palette.positive,
  },
  statusDotNeutral: {
    backgroundColor: palette.textSubtle,
  },
  statusDotWarning: {
    backgroundColor: palette.warning,
  },
  statusDotDanger: {
    backgroundColor: palette.danger,
  },
  heroMetaRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
  },
  heroMetaCard: {
    flexGrow: 1,
    minWidth: 150,
    borderRadius: 18,
    padding: 14,
    gap: 8,
    backgroundColor: palette.surfaceAlt,
    borderWidth: 1,
    borderColor: palette.border,
  },
  heroMetaLabel: {
    color: palette.textSubtle,
    fontSize: 11,
    textTransform: "uppercase",
    letterSpacing: 1.3,
  },
  heroMetaValue: {
    color: palette.text,
    fontSize: 18,
    fontWeight: "700",
  },
  card: {
    backgroundColor: palette.card,
    borderRadius: 24,
    padding: 20,
    borderWidth: 1,
    borderColor: palette.border,
    gap: 16,
    width: "100%",
    maxWidth: 640,
  },
  sectionTitle: {
    color: palette.text,
    fontSize: 20,
    fontWeight: "700",
  },
  sectionHeader: {
    gap: 6,
  },
  sectionKicker: {
    color: palette.textSubtle,
    fontSize: 11,
    textTransform: "uppercase",
    letterSpacing: 1.8,
  },
  input: {
    backgroundColor: palette.surface,
    color: palette.text,
    borderWidth: 1,
    borderColor: palette.borderSoft,
    borderRadius: 16,
    paddingHorizontal: 15,
    paddingVertical: 14,
    fontSize: 15,
  },
  label: {
    color: palette.textSubtle,
    fontSize: 12,
    marginBottom: 7,
    textTransform: "uppercase",
    letterSpacing: 1.1,
  },
  helperText: {
    color: palette.textSubtle,
    lineHeight: 21,
    fontSize: 14,
  },
  row: {
    flexDirection: "row",
    gap: 12,
  },
  flex: {
    flex: 1,
  },
  sheetBox: {
    width: 104,
  },
  segment: {
    flexDirection: "row",
    backgroundColor: palette.surfaceAlt,
    borderRadius: 18,
    padding: 4,
    gap: 6,
  },
  segmentButton: {
    flex: 1,
    borderRadius: 14,
    paddingVertical: 12,
    alignItems: "center",
  },
  segmentButtonActive: {
    backgroundColor: palette.accentSoft,
  },
  segmentText: {
    color: palette.textSubtle,
    fontWeight: "700",
    letterSpacing: 0.4,
  },
  segmentTextActive: {
    color: palette.accentText,
  },
  toggleRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 14,
  },
  mappingGrid: {
    gap: 12,
  },
  mappingRow: {
    gap: 7,
  },
  mappingLabel: {
    color: palette.textMuted,
    fontSize: 13,
  },
  mappingInput: {
    backgroundColor: palette.surface,
    color: palette.text,
    borderWidth: 1,
    borderColor: palette.borderSoft,
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  primaryButton: {
    backgroundColor: palette.accent,
    borderRadius: 18,
    minHeight: 54,
    paddingHorizontal: 18,
    paddingVertical: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  primaryButtonText: {
    color: "#05211C",
    fontSize: 16,
    fontWeight: "800",
  },
  secondaryButton: {
    backgroundColor: palette.secondaryButton,
    borderRadius: 16,
    minHeight: 50,
    paddingVertical: 12,
    paddingHorizontal: 16,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: palette.borderSoft,
  },
  secondaryButtonText: {
    color: palette.text,
    fontWeight: "700",
  },
  ghostButton: {
    borderRadius: 16,
    minHeight: 48,
    paddingVertical: 10,
    paddingHorizontal: 14,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: palette.borderSoft,
    backgroundColor: "transparent",
  },
  ghostButtonText: {
    color: palette.textMuted,
    fontWeight: "700",
  },
  buttonDisabled: {
    opacity: 0.52,
  },
  resultLine: {
    color: palette.textMuted,
    fontSize: 14,
    lineHeight: 21,
  },
  resultActions: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
  },
  mappingResult: {
    color: palette.text,
    fontSize: 14,
    lineHeight: 22,
  },
  statList: {
    gap: 10,
  },
  statRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 16,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.surfaceAlt,
    borderRadius: 16,
    paddingVertical: 13,
    paddingHorizontal: 14,
  },
  statLabel: {
    color: palette.textMuted,
    flex: 1,
    paddingRight: 12,
    fontSize: 13,
  },
  statValue: {
    color: palette.text,
    fontWeight: "700",
    fontSize: 14,
  },
  screenHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  screenHeaderSpacer: {
    width: 84,
  },
  inputStack: {
    gap: 12,
  },
  actionRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
  },
  actionPrimary: {
    flexGrow: 1,
    minWidth: 180,
  },
  actionSecondary: {
    flexGrow: 1,
    minWidth: 150,
  },
  sourceChip: {
    borderRadius: 18,
    paddingVertical: 12,
    paddingHorizontal: 14,
    backgroundColor: palette.surfaceAlt,
    borderWidth: 1,
    borderColor: palette.border,
    gap: 4,
  },
  sourceChipLabel: {
    color: palette.textSubtle,
    fontSize: 11,
    textTransform: "uppercase",
    letterSpacing: 1.2,
  },
  sourceChipValue: {
    color: palette.text,
    fontSize: 14,
    fontWeight: "600",
  },
  sourceChipMuted: {
    color: palette.textSubtle,
  },
  loadingStateCard: {
    borderRadius: 22,
    padding: 18,
    gap: 10,
    backgroundColor: palette.surfaceAlt,
    borderWidth: 1,
    borderColor: palette.border,
  },
  loadingHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  loadingStateTitle: {
    color: palette.text,
    fontSize: 17,
    fontWeight: "700",
  },
  loadingStateText: {
    color: palette.textMuted,
    fontSize: 14,
    lineHeight: 22,
  },
  spotlightCard: {
    borderRadius: 24,
    padding: 18,
    gap: 12,
    backgroundColor: "#050505",
    borderWidth: 1,
    borderColor: palette.borderSoft,
  },
  spotlightHeaderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 12,
  },
  spotlightLabel: {
    color: palette.text,
    fontSize: 18,
    fontWeight: "700",
  },
  spotlightValue: {
    fontSize: 40,
    fontWeight: "800",
    letterSpacing: -1,
  },
  spotlightFootnote: {
    color: palette.textMuted,
    fontSize: 13,
    lineHeight: 20,
  },
  metricPositive: {
    color: palette.positive,
  },
  metricNegative: {
    color: palette.danger,
  },
  metricNeutral: {
    color: palette.text,
  },
  summaryGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
  },
  summaryCard: {
    flexGrow: 1,
    minWidth: 152,
    borderRadius: 18,
    padding: 14,
    gap: 8,
    backgroundColor: palette.surfaceAlt,
    borderWidth: 1,
    borderColor: palette.border,
  },
  summaryLabel: {
    color: palette.textSubtle,
    fontSize: 11,
    textTransform: "uppercase",
    letterSpacing: 1.2,
  },
  summaryValue: {
    color: palette.text,
    fontSize: 24,
    fontWeight: "800",
  },
  inlineMetaRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  inlineMetaPill: {
    borderRadius: 999,
    paddingVertical: 9,
    paddingHorizontal: 12,
    backgroundColor: palette.surfaceAlt,
    borderWidth: 1,
    borderColor: palette.border,
  },
  inlineMetaText: {
    color: palette.textMuted,
    fontSize: 12,
    fontWeight: "600",
  },
  emptyStateCard: {
    borderRadius: 22,
    padding: 18,
    gap: 8,
    backgroundColor: palette.surfaceAlt,
    borderWidth: 1,
    borderColor: palette.border,
  },
  emptyStateTitle: {
    color: palette.text,
    fontSize: 16,
    fontWeight: "700",
  },
  emptyStateText: {
    color: palette.textMuted,
    fontSize: 14,
    lineHeight: 22,
  },
  monoText: {
    color: palette.text,
    fontSize: 13,
  },
  errorCard: {
    borderColor: "#472727",
    backgroundColor: "#160D0D",
  },
  errorText: {
    color: palette.danger,
  },
});
